import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./layout.css";
import BirdContainer from "./components/Bird/BirdContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col">
          <div className="banner flex-grow overflow-y-auto">
            <div className="absolute top-10 left-10 text-lg text-white">
              Ponte Web
            </div>
            <div className="h-96">
              <BirdContainer />
            </div>
          </div>
          <main className="h-2/3 overflow-y-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
